### ISSUE TITLE
Queries not working with strawberry-graphql==0.121.0

### ISSUE THREAD

**Issue by edomora97** [strawberry-graphql/strawberry-graphql-django#152]
## Describe the Bug

Using the last stable release of `strawberry-graphql` (0.121.0) all the queries fail with:

```json
{
  "data": null,
  "errors": [
    {
      "message": "'NoneType' object has no attribute 'colors'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "colors"
      ]
    }
  ]
}
```

With `strawberry-graphql==0.120.0` everything works fine.

## Reproducing

It's enough to use the example project in this repo at `examples/django`.

Adding `strawberry-graphql = "==0.121.0"` to `pyproject.toml` and running `poetry update` makes the above error happen.
With `strawberry-graphql = "==0.120.0"` the error is not present.

## System Information

 - Strawberry version (if applicable): 0.121.0

## Additional Context

Release 0.121.0 contains a single commit coming from https://github.com/strawberry-graphql/strawberry/pull/2037.

**Comment by patrick91** [comment]
Ciao @edomora97! I have a PR that should fix this here: https://github.com/strawberry-graphql/strawberry/pull/2038 😊

**Comment by devkral** [comment]
may I ask: can't we lock the version to strawberry <0.121 as quick fix until the issue is resolved?

**Comment by edomora97** [comment]
I can confirm that with 0.121.1 everything works again.

**Comment by patrick91** [comment]
@devkral should be ok now! 

we'll try to find some ways to make sure we don't break strawberry django in future, sorry about the breakages 😊

I'll close the issue, let me know if there's any other problems :)
